use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    println!("Hello, day 8");
    Ok(())
}